sudo: required
matrix:
  fast_finish: true
services:
- docker
before_install:
- docker pull bioplatformsaustralia/bioplatforms-composer
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- chmod 755 ~/.docker
- chmod 644 ~/.docker/config.json
- export "GIT_BRANCH=$TRAVIS_BRANCH"
- test x"$TRAVIS_PULL_REQUEST_BRANCH" != x"" && export "GIT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH" || echo "This build is not a PR."
- export "BRANCH_NAME=$GIT_BRANCH"
- ./travis-build.sh
- ./travis-prodbuild.sh

env:
  global:
    - DOCKER_USERNAME: devredbox
    - secure: hnUxSpouKMp8qrBKmUT1eib54XE/61QYf3F8cx/rcFwGRyrhUrmzabYvAbbvxFu+AADZ7FXQl7D3Yri5PElXWazRCf2cNg8PJ17oYn92bUY3xZjr+OeWBo/Oy9gaI7aKwx3DzZ5FoG6P0RujRDrfOYSjxRFmjBnUhya06ODCsUPXramjuUInKfcVlW5Ysrki9foFauPctVZ+Y+WenMnkgPJpubIU84LNXguhb1OIDKq8FyEjjEKIBWEAS4Z7Xj9egvMoKOdTddeMUl3uGOQds6qLGdnFUJxLlCGuaYrIxi4vwd12Ho/px7dotB8t4K15dIecz+XPrdG0f0LEdiRzmoepqWNVeu88B3A0hmL17wk/TmjAWrpnEjMCHU84yUnPPgzaVyN9NFhqYQUTFgCg1yk4mjxBSy5G1klir/8uggjFRUNYvdv3/v/3PAum3dvpX09GXy9FsL7rHJhyU/pWAyE3Y9x9m5e8KT+TI8i/gqvKBWwmNsKLG/WNeSlyDzc+WdZnjsuKWr5ECPcIO0dHf/vo4/KGwku9cMxh3GGZSlCDnUdKoaUYlT3f/8DcG/NwK1ajz87/Wra05D++sK2gAL7/hQVko/6fZIMQhBI8bjMIItcbW4BcARlOS2SrG1TwCq39ee1aLl6iVEqTQDc8gVmIpzDWa8JhFiibMuWiKGE=
