sudo: required
matrix:
  fast_finish: true
services:
- docker
before_install:
- docker pull bioplatformsaustralia/bioplatforms-composer
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- chmod 755 ~/.docker
- chmod 644 ~/.docker/config.json
- export "GIT_BRANCH=$TRAVIS_BRANCH"
- test x"$TRAVIS_PULL_REQUEST_BRANCH" != x"" && export "GIT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH" || echo "This build is not a PR."
- export "BRANCH_NAME=$GIT_BRANCH"
- ./travis-build.sh
- ./travis-prodbuild.sh

env:
  global:
    - DOCKER_USERNAME: gbowland
    - secure: "cAlTzu/eJWtVuwxdQTQ50l+PENl/BQvI7LwSmvDjCOqN4X0Cyn2e2iSkKgvrosRitOVGZ/lzsPcHfsm1rpZfvPcZNHks0Zn4H4lVe0mwtpAGOkzasL4peBrYc8oIuGpiG1r0YslZfyFoFL/yr1YauilfiDW4B3Z99RYQnsmZq5Ll5zJQcabdjPhJ1w+90DD78cNXVZXdffFG4+iWc/I/XpSTNDmdbDipZRRh4oNf0saWAJbe20h/vvCBRMFtdNQ1ga6iymfEtKsH4Relr5sEb3hRuXwrsvexMUOOPzFgOEcmkSrdbpqGVGPpZjq2mDQldcvlbVJR12r2ygwWhwCnObC8X4b6tPpTjj5tZ7awh11lNjx7HgbEn1zDJOOuH2UycTDeCgY9Kl4MsaB7SMnLp6k335scRBMoWkj8Hsza55qmGoetqUb3SMo7bAOCYIYZP7X1sHk8qqRFiAWCQmp10na+3oQrEL+2CihcGcXuXG+kP1l1fOVymIWE6TBVYkkXnacI1xI0tCjF4IriyO2EfO+GcNmKRv1sr9x4YAlN4dRyqvJkOPnYLkcuZQTyhOarz7aHV8xV1H891T8SihWI5oSCt5ZOaYcejRZFR1xDsMhAySWO9FSRQsdsX9sqP/JhD/IoCRIb5SVxSXSvu32JVh1vXJYw+OynswpQk91Dd2s="

