version: '2'
services:

  dev:
    build:
      context: ./
      args:
        http_proxy:
    image: muccg/${CCG_PROJECT}:${GIT_BRANCH}

  latest:
    extends:
      file: docker-compose-build.yml
      service: dev
    image: muccg/${CCG_PROJECT}:latest

  latest-date:
    extends:
      file: docker-compose-build.yml
      service: dev
    image: muccg/${CCG_PROJECT}:latest-${CCG_BUILD_DATE}
