version: '2'
services:

  dev:
    build:
      context: ./
      args:
        http_proxy:
    image: bioplatformsaustralia/${BIOPLATFORMS_PROJECT}:${GIT_BRANCH}

  prod:
    extends:
      file: docker-compose-build.yml
      service: dev
    image: bioplatformsaustralia/${BIOPLATFORMS_PROJECT}:${GIT_TAG}

  prod-date:
    extends:
      file: docker-compose-build.yml
      service: dev
    image: bioplatformsaustralia/${BIOPLATFORMS_PROJECT}:${GIT_TAG}-${BIOPLATFORMS_BUILD_DATE}

  latest:
    extends:
      file: docker-compose-build.yml
      service: dev
    image: bioplatformsaustralia/${BIOPLATFORMS_PROJECT}:latest

  latest-date:
    extends:
      file: docker-compose-build.yml
      service: dev
    image: bioplatformsaustralia/${BIOPLATFORMS_PROJECT}:latest-${BIOPLATFORMS_BUILD_DATE}
