# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker pull bioplatformsaustralia/bioplatforms-composer
          apt-get install -y iproute2
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          chmod 755 ~/.docker
          chmod 644 ~/.docker/config.json
          export "GIT_BRANCH=$TRAVIS_BRANCH"
          test x"$TRAVIS_PULL_REQUEST_BRANCH" != x"" && \
            export "GIT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH" || echo "This build is not a PR."
          export "BRANCH_NAME=$GIT_BRANCH"
          "./travis-build.sh"
          "./circleci-prodbuild.sh"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master